export const ADD_TO_ORDER_HISTORY = 'ADD_TO_ORDER_HISTORY'
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS'
export const StatusTypes = {
  PENDING: 'PENDING',
  SHIPPED: 'SHIPPED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};
